from scipy.optimize import linprog
from pulp import LpMaximize, LpProblem, LpStatus, lpSum, LpVariable

# To add a recipe
# 1. For each output - add made resource variable (add _2 if not first)
# 1. For each output - if not first add kept resource variable
# 1. For each input  - if not first add kept + made resource variable (probably already exists tho)
# 2. Add iteration w/ recipe name
# 3. For each (input, ouput) pair - add input/output * made_{output} to input constraint 
# 4. For each output - add integer iteration constraint
# 5. For each output - if not first add resource sink optimization

# Create the model
model = LpProblem(name="small-problem", sense=LpMaximize)

# Initialize the decision variables
kept_iron_ore = LpVariable(name="kept_iron_ore", lowBound=0)
kept_copper_ore = LpVariable(name="kept_copper_ore", lowBound=0)
kept_limestone = LpVariable(name="kept_limestone", lowBound=0)
kept_caterium_ore = LpVariable(name="kept_caterium_ore", lowBound=0)
kept_sulfur = LpVariable(name="kept_sulfur", lowBound=0)
kept_raw_quartz = LpVariable(name="kept_raw_quartz", lowBound=0)
kept_coal = LpVariable(name="kept_coal", lowBound=0)
kept_crude_oil = LpVariable(name="kept_crude_oil", lowBound=0)
kept_bauxite = LpVariable(name="kept_bauxite", lowBound=0)
kept_water = LpVariable(name="kept_water", lowBound=0)
kept_nitrogen_gas = LpVariable(name="kept_nitrogen_gas", lowBound=0)
kept_uranium = LpVariable(name="kept_uranium", lowBound=0)
made_iron_ingot = LpVariable(name="made_iron_ingot", lowBound=0)
kept_iron_ingot = LpVariable(name="kept_iron_ingot", lowBound=0)
made_iron_plate = LpVariable(name="made_iron_plate", lowBound=0)
kept_iron_plate = LpVariable(name="kept_iron_plate", lowBound=0)
made_iron_rod = LpVariable(name="made_iron_rod", lowBound=0)
kept_iron_rod = LpVariable(name="kept_iron_rod", lowBound=0)
made_screw_1 = LpVariable(name="made_screw_1", lowBound=0)
made_screw_2 = LpVariable(name="made_screw_2", lowBound=0)
kept_screw = LpVariable(name="kept_screw", lowBound=0)
kept_copper_ingot = LpVariable(name="kept_copper_ingot", lowBound=0)
made_copper_ingot_1 = LpVariable(name="made_copper_ingot_1", lowBound=0)
made_copper_ingot_2 = LpVariable(name="made_copper_ingot_2", lowBound=0)
kept_concrete = LpVariable(name="kept_concrete", lowBound=0)
made_concrete = LpVariable(name="made_concrete", lowBound=0)
kept_caterium_ingot = LpVariable(name="kept_caterium_ingot", lowBound=0)
made_caterium_ingot = LpVariable(name="made_caterium_ingot", lowBound=0)
kept_silica = LpVariable(name="kept_silica", lowBound=0)
made_silica = LpVariable(name="made_silica", lowBound=0)
kept_steel_ingot = LpVariable(name="kept_steel_ingot", lowBound=0)
made_steel_ingot_1 = LpVariable(name="made_steel_ingot_1", lowBound=0)
made_steel_ingot_2 = LpVariable(name="made_steel_ingot_2", lowBound=0)
kept_copper_sheet = LpVariable(name="kept_copper_sheet", lowBound=0)
made_copper_sheet_1 = LpVariable(name="made_copper_sheet_1", lowBound=0)
kept_steel_beam = LpVariable(name="kept_steel_beam", lowBound=0)
made_steel_beam = LpVariable(name="made_steel_beam", lowBound=0)
kept_steel_pipe = LpVariable(name="kept_steel_pipe", lowBound=0)
made_steel_pipe = LpVariable(name="made_steel_pipe", lowBound=0)
kept_wire = LpVariable(name="kept_wire", lowBound=0)
made_wire = LpVariable(name="made_wire", lowBound=0)
kept_cable = LpVariable(name="kept_cable", lowBound=0)
made_cable = LpVariable(name="made_cable", lowBound=0)
kept_quickwire = LpVariable(name="kept_quickwire", lowBound=0)
made_quickwire = LpVariable(name="made_quickwire", lowBound=0)
kept_quartz_crystal = LpVariable(name="kept_quartz_crystal", lowBound=0)
made_quartz_crystal = LpVariable(name="made_quartz_crystal", lowBound=0)
kept_reinforced_iron_plate = LpVariable(name="kept_reinforced_iron_plate", lowBound=0)
made_reinforced_iron_plate_1 = LpVariable(name="made_reinforced_iron_plate_1", lowBound=0)
made_reinforced_iron_plate_2 = LpVariable(name="made_reinforced_iron_plate_2", lowBound=0)
made_reinforced_iron_plate_3 = LpVariable(name="made_reinforced_iron_plate_3", lowBound=0)
kept_modular_frame = LpVariable(name="kept_modular_frame", lowBound=0)
made_modular_frame_1 = LpVariable(name="made_modular_frame_1", lowBound=0)
made_modular_frame_2 = LpVariable(name="made_modular_frame_2", lowBound=0)
kept_encased_industrial_beam = LpVariable(name="kept_encased_industrial_beam", lowBound=0)
made_encased_industrial_beam = LpVariable(name="made_encased_industrial_beam", lowBound=0)
kept_smart_plating = LpVariable(name="kept_smart_plating", lowBound=0)
made_smart_plating  = LpVariable(name="made_smart_plating ", lowBound=0)
kept_rotor = LpVariable(name="kept_rotor", lowBound=0)
made_rotor_1 = LpVariable(name="made_rotor_1", lowBound=0)
made_rotor_2 = LpVariable(name="made_rotor_2", lowBound=0)
kept_plastic = LpVariable(name="kept_plastic", lowBound=0)
made_plastic_1 = LpVariable(name="made_plastic_1", lowBound=0)
kept_rubber = LpVariable(name="kept_rubber", lowBound=0)
made_rubber_1 = LpVariable(name="made_rubber_1", lowBound=0)
kept_heavy_oil_residue = LpVariable(name="kept_heavy_oil_residue", lowBound=0)
made_heavy_oil_residue_from_plastic = LpVariable(name="made_heavy_oil_residue_from_plastic", lowBound=0)
made_heavy_oil_residue_from_rubber = LpVariable(name="made_heavy_oil_residue_from_rubber", lowBound=0)
kept_petroleum_coke = LpVariable(name="kept_petroleum_coke", lowBound=0)
made_petroleum_coke  = LpVariable(name="made_petroleum_coke", lowBound=0)
#kept_ = LpVariable(name="", lowBound=0)
#made_ = LpVariable(name="", lowBound=0)

cast_screw_iterations = LpVariable(name="cast_screw_iterations", lowBound=0, cat="Integer")
screw_iterations = LpVariable(name="screw_iterations", lowBound=0, cat="Integer")
iron_plate_iterations = LpVariable(name="iron_plate_iterations", lowBound=0, cat="Integer")
iron_rod_iterations = LpVariable(name="iron_rod_iterations", lowBound=0, cat="Integer")
iron_ingot_iterations = LpVariable(name="iron_ingot_iterations", lowBound=0, cat="Integer")
copper_ingot_iterations = LpVariable(name="copper_ingot_iterations", lowBound=0, cat="Integer")
copper_alloy_ingot_iterations = LpVariable(name="copper_alloy_ingot_iterations", lowBound=0, cat="Integer")
caterium_ingot_iterations = LpVariable(name="caterium_ingot_iterations", lowBound=0, cat="Integer")
steel_ingot_iterations = LpVariable(name="steel_ingot_iterations", lowBound=0, cat="Integer")
solid_steel_ingot_iterations = LpVariable(name="solid_steel_ingot_iterations", lowBound=0, cat="Integer")
concrete_iterations = LpVariable(name="concrete_iterations", lowBound=0, cat="Integer")
silica_iterations = LpVariable(name="silica_iterations", lowBound=0, cat="Integer")
copper_sheet_iterations = LpVariable(name="copper_sheet_iterations", lowBound=0, cat="Integer")
steel_beam_iterations = LpVariable(name="steel_beam_iterations", lowBound=0, cat="Integer")
steel_pipe_iterations = LpVariable(name="steel_pipe_iterations", lowBound=0, cat="Integer")
wire_iterations = LpVariable(name="wire_iterations", lowBound=0, cat="Integer")
cable_iterations = LpVariable(name="cable_iterations", lowBound=0, cat="Integer")
quickwire_iterations = LpVariable(name="quickwire_iterations", lowBound=0, cat="Integer")
quartz_crystal_iterations = LpVariable(name="quartz_crystal_iterations", lowBound=0, cat="Integer")
reinforced_iron_plate_iterations = LpVariable(name="reinforced_iron_plate_iterations", lowBound=0, cat="Integer")
bolted_iron_plate_iterations = LpVariable(name="bolted_iron_plate_iterations", lowBound=0, cat="Integer")
adhered_iron_plate_iterations = LpVariable(name="adhered_iron_plate_iterations", lowBound=0, cat="Integer")
modular_frame_iterations = LpVariable(name="modular_frame_iterations", lowBound=0, cat="Integer")
steeled_frame_iterations = LpVariable(name="steeled_frame_iterations", lowBound=0, cat="Integer")
encased_industrial_beam_iterations = LpVariable(name="encased_industrial_beam_iterations", lowBound=0, cat="Integer")
rotor_iterations = LpVariable(name="rotor_iterations", lowBound=0, cat="Integer")
copper_rotor_iterations = LpVariable(name="copper_rotor_iterations", lowBound=0, cat="Integer")
smart_plating_iterations = LpVariable(name="smart_plating_iterations", lowBound=0, cat="Integer")
plastic_iterations = LpVariable(name="plastic_iterations", lowBound=0, cat="Integer")
rubber_iterations = LpVariable(name="rubber_iterations", lowBound=0, cat="Integer")
petroleum_coke_iterations = LpVariable(name="petroleum_coke_iterations", lowBound=0, cat="Integer")
# _iterations = LpVariable(name="", lowBound=0, cat="Integer")
 
# raw resource input constraint
model += (kept_iron_ore + made_iron_ingot + made_steel_ingot_1 + 5/20 * made_copper_ingot_2 <= 601)
model += (kept_copper_ore + made_copper_ingot_1 + 10/20 * made_copper_ingot_2 <= 601)
model += (kept_limestone + 3 * made_concrete <= 0)
model += (kept_caterium_ore + 3 * made_caterium_ingot <= 0)
model += (kept_sulfur <= 0)
model += (kept_raw_quartz + 3/5 * made_silica + 5/3 * made_quartz_crystal <= 0)
model += (kept_coal + made_steel_ingot_1 + 2/3 * made_steel_ingot_2 <= 601)
model += (kept_crude_oil + 3/2 * made_rubber_1 + 3/2 * made_plastic_1 <= 601)
model += (kept_bauxite <= 0)
model += (kept_water <= 0)
model += (kept_nitrogen_gas <= 0)
model += (kept_uranium <= 0)

# resource use contraint
model += (kept_iron_ingot + 3/2 * made_iron_plate + made_iron_rod + 5/20 * made_screw_2 + 2/3 * made_steel_ingot_2 == made_iron_ingot) 
model += (kept_iron_plate + 6 * made_reinforced_iron_plate_1 + 6 * made_reinforced_iron_plate_2 + 3 * made_reinforced_iron_plate_3 == made_iron_plate)
model += (kept_iron_rod + 1/4 * made_screw_1 + 6 * made_modular_frame_1 + 5 * made_rotor_1 == made_iron_rod)
model += (kept_screw + 12 * made_reinforced_iron_plate_1 + 50/3 * made_reinforced_iron_plate_2 + 25 * made_rotor_1 + 52/3 * made_rotor_2 == made_screw_1 + made_screw_2)
model += (kept_copper_ingot + 2 * made_copper_sheet_1 + 1/2 * made_wire == made_copper_ingot_1 + made_copper_ingot_2)
model += (kept_caterium_ingot + 1/5 * made_quickwire == made_caterium_ingot)
model += (kept_steel_ingot + 4 * made_steel_beam + 3/2 * made_steel_pipe == made_steel_ingot_1 + made_steel_ingot_2)
model += (kept_concrete + 5 * made_encased_industrial_beam == made_concrete)
model += (kept_silica == made_silica)
model += (kept_copper_sheet + 2 * made_rotor_2 == made_copper_sheet_1)
model += (kept_steel_beam + 4 * made_encased_industrial_beam == made_steel_beam)
model += (kept_steel_pipe + 10/3 * made_modular_frame_2 == made_steel_pipe)
model += (kept_wire + 2 * made_cable == made_wire)
model += (kept_cable == made_cable)
model += (kept_quickwire == made_quickwire)
model += (kept_quartz_crystal == made_quartz_crystal)
model += (kept_reinforced_iron_plate + 3/2 * made_modular_frame_1 + 2/3 * made_modular_frame_2 + made_smart_plating == made_reinforced_iron_plate_1 + made_reinforced_iron_plate_2 + made_reinforced_iron_plate_3)
model += (kept_modular_frame == made_modular_frame_1 + made_modular_frame_2)
model += (kept_encased_industrial_beam == made_encased_industrial_beam)
model += (kept_rotor + made_smart_plating == made_rotor_1 + made_rotor_2)
model += (kept_smart_plating == made_smart_plating)
model += (kept_plastic == made_plastic_1)
model += (kept_rubber + made_reinforced_iron_plate_3 == made_rubber_1)
model += (kept_heavy_oil_residue + 4/12 * made_petroleum_coke == made_heavy_oil_residue_from_plastic + made_heavy_oil_residue_from_rubber)
model += (kept_petroleum_coke == made_petroleum_coke)

# recipe use constraint
model += (made_screw_2 * 1/20 == cast_screw_iterations)
model += (made_screw_1 * 1/4 == screw_iterations)
model += (made_iron_plate * 1/2 == iron_plate_iterations)
model += (made_iron_rod == iron_rod_iterations)
model += (made_iron_ingot == iron_ingot_iterations)
model += (made_copper_ingot_1 == copper_ingot_iterations)
model += (made_copper_ingot_2 * 1/20 == copper_alloy_ingot_iterations)
model += (made_caterium_ingot == caterium_ingot_iterations)
model += (made_steel_ingot_1 * 1/3  == steel_ingot_iterations)
model += (made_steel_ingot_2 * 1/3  == solid_steel_ingot_iterations)
model += (made_concrete == concrete_iterations)
model += (made_silica * 1/5 == silica_iterations)
model += (made_copper_sheet_1 == copper_sheet_iterations)
model += (made_steel_beam == steel_beam_iterations)
model += (made_steel_pipe * 1/2 == steel_pipe_iterations)
model += (made_wire * 1/2 == wire_iterations)
model += (made_cable == cable_iterations)
model += (made_quickwire * 1/5 == quickwire_iterations)
model += (made_quartz_crystal * 1/3 == quartz_crystal_iterations)
model += (made_reinforced_iron_plate_1 == reinforced_iron_plate_iterations)
model += (made_reinforced_iron_plate_2 * 1/3 == bolted_iron_plate_iterations)
model += (made_reinforced_iron_plate_3 == adhered_iron_plate_iterations)
model += (made_modular_frame_1 * 1/2 == modular_frame_iterations)
model += (made_modular_frame_2 * 1/3 == steeled_frame_iterations)
model += (made_encased_industrial_beam == encased_industrial_beam_iterations)
model += (made_rotor_1 == rotor_iterations)
model += (made_rotor_2 * 1/3 == copper_rotor_iterations)
model += (made_smart_plating == smart_plating_iterations)
model += (made_plastic_1 * 1/2 == plastic_iterations)
model += (made_heavy_oil_residue_from_plastic == plastic_iterations)
model += (made_rubber_1 * 1/2 == rubber_iterations)
model += (made_heavy_oil_residue_from_rubber * 1/2 == rubber_iterations)
model += (made_petroleum_coke * 1/12 == petroleum_coke_iterations)
# model += (made_* 1/2 == _iterations)

# Add the objective function to the model
# sink maximize
model += lpSum([kept_iron_ore, 3 * kept_copper_ore, 2 * kept_limestone, 7 * kept_caterium_ore, 11 * kept_sulfur, 15 * kept_raw_quartz, 3 * kept_coal, 8 * kept_bauxite, 0 * kept_uranium, 2 * kept_iron_ingot, 8 * kept_iron_plate, 4 * kept_iron_rod, 2 * kept_screw, 6 * kept_copper_ingot, 12 * kept_concrete, 42 * kept_caterium_ingot, 20 * kept_silica, 8 * kept_steel_ingot, 24 * kept_copper_sheet, 64 * kept_steel_beam, 24 * kept_steel_pipe, 6 * kept_wire, 24 * kept_cable, 17 * kept_quickwire, 50 * kept_quartz_crystal, 120 * kept_reinforced_iron_plate, 408 * kept_modular_frame, 632 * kept_encased_industrial_beam, 140 * kept_rotor, 520 * kept_smart_plating, 75 * kept_plastic, 60 * kept_rubber, 20 * kept_petroleum_coke ])

# Solve the problem
status = model.solve()

print(f"status: {model.status}, {LpStatus[model.status]}")
print(f"objective: {model.objective.value()}")
print("-")
for var in model.variables():
    if round(var.value(),10) != 0 and "iterations" in var.name:
        print(f"{var.name}: {var.value()}")
print("-")
for var in model.variables():
    if round(var.value(),10) != 0 and "made" in var.name:
        print(f"{var.name}: {var.value()}")
print("-")
for var in model.variables():
    if round(var.value(),10) != 0 and "kept" in var.name:
        print(f"{var.name}: {var.value()}")
#for name, constraint in model.constraints.items():
#    print(f"{name}: {constraint.value()}")
